{% set name = "pycashier" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycashier-{{ version }}.tar.gz
  sha256: 3c80c8e7df36633215d40b05466294aa9c98b022bd6987aea001cfdb5bf6d578

build:
  number: 0
  noarch: python
  entry_points:
    - pycashier = pycashier.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.10
    - poetry
  run:
    - python >=3.6,<3.10
    - rich >=12.0.0
    - click-rich-help >=22.1.0
    - tomlkit >=0.10.1

test:
  imports:
    - pycashier
  commands:
    - pip check
    - pycashier --help
  requires:
    - pip

about:
  home: https://github.com/brocklab/pycashier/
  summary: cash in on DNA barcode tags
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
