{% set name = "pycashier" %}
{% set version = "0.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycashier-{{ version }}.tar.gz
  sha256: b36f8390c8e687a5fe427a6dafa58eb72dea6f999f54dc43302b4565a52301dd

build:
  number: 0
  noarch: python
  entry_points:
    - pycashier = pycashier.pycashier:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.10
    - poetry
  run:
    - python >=3.6,<3.10
    - rich >=10.12.0,<11.0.0

test:
  imports:
    - pycashier
  commands:
    - pip check
    - pycashier --help
  requires:
    - pip

about:
  home: https://github.com/brocklab/pycashier/
  summary: cash in on expressed barcode tags
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
